<?php
    function comment_buddy_menu() {
        $items = array();
        $items['comment_buddy'] = array(
            'title' => "Thanks for commenting!",
            'page callback' => 'new_comment',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        $items['comment_edit'] = array(
            'title' => "You edited your comment!",
            'page callback' => 'edit_comment',
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        $items['comment_delete'] = array(
            'title' => "You deleted your comment!",
            'page callback' => "delete_comment",
            'access callback' => TRUE,
            'type' => MENU_CALLBACK,
        );
        return $items;
    }

    function new_comment() {
        return '<p>You are about to make a comment!</p>';
    }

    function edit_comment() {
        return '<p>You edited a comment!</p>';
    }

    function delete_comment() {
        return '<p>You deleted a comment!</p>';
    }

    function comment_buddy_comment_update() {
        $_GET['destination'] = 'comment_edit';
    }

    function comment_buddy_comment_insert() {
        $_GET['destination'] = 'comment_buddy';
    }

    function comment_buddy_comment_delete() {
        $_GET['destination'] = 'comment_delete';
    }
